### ISSUE TITLE
the "plustek-8100-6x7" post is unable to access

### ISSUE THREAD

**Issue by MOOOWOOO** [enthdegree/sane-backends#1]
as title said, the post is unable to access, shows 404.

and https://ebn0.net/plustek-8100-6x7.html is also unable to access

does anyone can help recover the post ?

**Comment by ThoStaKa** [comment]
I have no idea on where that link should go, but I believe that this link at least is quite informative: https://www.diyphotography.net/how-to-modify-the-plustek-8100-35mm-film-scanner-to-scan-medium-format-roll-film/

**Comment by ThoStaKa** [comment]
Well, look here: I found some old snapshots from march via archive.org.
https://web.archive.org/web/20230327144441/https://ebn0.net/plustek-8100-6x7.html

**Comment by MOOOWOOO** [comment]
> Well, look here: I found some old snapshots from march via archive.org. https://web.archive.org/web/20230327144441/https://ebn0.net/plustek-8100-6x7.html

THANKS A LOOOOOOOOOT !!!

About the year past, i switch my apartment several times, and i just restart shooting films and do self developing. Now i can modify my 8200 to scan my 6x7 films~
